name: RS485 Sniffer
slug: rs485_sniffer
description: Sniffer RS485/Modbus traffic and publishes to MQTT
version: "1.0.12"

arch:
  - aarch64

startup: application
boot: auto
init: false

privileged:
  - SYS_RAWIO

usb: true
uart: true

devices:
  - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AW6CH20W-if00-port0

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
