name: RS485 Sniffer
slug: rs485_sniffer
description: Sniffer RS485/Modbus traffic and publishes to MQTT
version: "1.0.4"

arch:
  - aarch64

init: false

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-no-s6:latest

options: {}
schema: {}
